import { useState, useEffect, Fragment } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { getToken } from "@/lib/api";
import { cn } from "@/lib/utils";
import { Mail, Loader2, CheckCircle2, XCircle, MinusCircle, RefreshCw } from "lucide-react";

type EmailStatus = "sent" | "failed" | "skipped";

type EmailLog = {
  id: number;
  type: string;
  toEmail: string;
  subject: string;
  status: EmailStatus;
  errorMessage: string | null;
  sentAt: string;
};

const TYPE_LABELS: Record<string, string> = {
  follow_up: "Follow-up",
  bug_report: "Bug Report",
  watcher_notification: "Watcher Notification",
  reminder_upcoming: "Upcoming Reminder",
  reminder_past_due: "Past-Due Reminder",
  summary: "Summary",
};

const TYPE_COLORS: Record<string, string> = {
  follow_up: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400",
  bug_report: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400",
  watcher_notification: "bg-violet-100 text-violet-800 dark:bg-violet-900/30 dark:text-violet-400",
  reminder_upcoming: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400",
  reminder_past_due: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400",
  summary: "bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-400",
};

const STATUS_CONFIG: Record<EmailStatus, { label: string; icon: React.ElementType; className: string }> = {
  sent: { label: "Sent", icon: CheckCircle2, className: "text-green-600 dark:text-green-400" },
  failed: { label: "Failed", icon: XCircle, className: "text-red-600 dark:text-red-400" },
  skipped: { label: "Skipped", icon: MinusCircle, className: "text-muted-foreground" },
};

function formatTime(iso: string) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) +
    " at " + d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
}

async function apiFetch(url: string) {
  return fetch(url, {
    headers: { Authorization: `Bearer ${getToken()}` },
  });
}

export default function AdminEmailLogsPage() {
  const [logs, setLogs] = useState<EmailLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<EmailStatus | "all">("all");
  const [expandedId, setExpandedId] = useState<number | null>(null);

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const r = await apiFetch("/api/admin/email-logs");
      if (r.ok) setLogs(await r.json());
    } finally {
      setLoading(false);
    }
  }

  const filtered = logs.filter((l) => {
    if (typeFilter !== "all" && l.type !== typeFilter) return false;
    if (statusFilter !== "all" && l.status !== statusFilter) return false;
    return true;
  });

  const counts = {
    sent: logs.filter((l) => l.status === "sent").length,
    failed: logs.filter((l) => l.status === "failed").length,
    skipped: logs.filter((l) => l.status === "skipped").length,
  };

  const allTypes = [...new Set(logs.map((l) => l.type))];

  return (
    <AppLayout>
      <div className="p-6 max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
              <Mail className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h1 className="text-xl font-bold">Email Log</h1>
              <p className="text-sm text-muted-foreground">All emails generated by the system — last 500 records</p>
            </div>
          </div>
          <button
            onClick={load}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm bg-muted hover:bg-muted/80 transition"
          >
            <RefreshCw className={cn("w-4 h-4", loading && "animate-spin")} />
            Refresh
          </button>
        </div>

        {/* Stats bar */}
        <div className="grid grid-cols-3 gap-3 mb-5">
          {(["sent", "failed", "skipped"] as EmailStatus[]).map((s) => {
            const cfg = STATUS_CONFIG[s];
            const Icon = cfg.icon;
            return (
              <button
                key={s}
                onClick={() => setStatusFilter(statusFilter === s ? "all" : s)}
                className={cn(
                  "flex items-center gap-3 bg-card border border-card-border rounded-xl p-4 text-left transition hover:border-primary/30",
                  statusFilter === s && "border-primary/50 bg-primary/5"
                )}
              >
                <Icon className={cn("w-5 h-5 flex-shrink-0", cfg.className)} />
                <div>
                  <p className="text-lg font-bold leading-none">{counts[s]}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{cfg.label}</p>
                </div>
              </button>
            );
          })}
        </div>

        {/* Filters */}
        <div className="flex items-center gap-2 mb-4 flex-wrap">
          <span className="text-xs text-muted-foreground font-medium">Type:</span>
          <button
            onClick={() => setTypeFilter("all")}
            className={cn("px-3 py-1 rounded-full text-xs font-medium transition", typeFilter === "all" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:text-foreground")}
          >
            All
          </button>
          {allTypes.map((t) => (
            <button
              key={t}
              onClick={() => setTypeFilter(typeFilter === t ? "all" : t)}
              className={cn("px-3 py-1 rounded-full text-xs font-medium transition", typeFilter === t ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:text-foreground")}
            >
              {TYPE_LABELS[t] ?? t}
            </button>
          ))}
        </div>

        {/* Table */}
        {loading ? (
          <div className="flex items-center justify-center py-16 text-muted-foreground">
            <Loader2 className="w-5 h-5 animate-spin mr-2" />
            Loading...
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-16 text-muted-foreground">
            <Mail className="w-10 h-10 mx-auto mb-3 opacity-30" />
            <p className="font-medium">No emails recorded yet</p>
            <p className="text-sm mt-1">Emails will appear here as the system sends them.</p>
          </div>
        ) : (
          <div className="bg-card border border-card-border rounded-xl overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-card-border bg-muted/40">
                  <th className="text-left px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">Status</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">Type</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider">Recipient</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider hidden md:table-cell">Subject</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-muted-foreground uppercase tracking-wider whitespace-nowrap">Sent At</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((log) => {
                  const cfg = STATUS_CONFIG[log.status];
                  const Icon = cfg.icon;
                  const isExpanded = expandedId === log.id;
                  return (
                    <Fragment key={log.id}>
                      <tr
                        onClick={() => setExpandedId(isExpanded ? null : log.id)}
                        className={cn(
                          "border-b border-card-border last:border-0 cursor-pointer hover:bg-muted/30 transition",
                          log.status === "failed" && "bg-red-500/5"
                        )}
                      >
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-1.5">
                            <Icon className={cn("w-4 h-4 flex-shrink-0", cfg.className)} />
                            <span className={cn("text-xs font-medium", cfg.className)}>{cfg.label}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", TYPE_COLORS[log.type] ?? "bg-muted text-muted-foreground")}>
                            {TYPE_LABELS[log.type] ?? log.type}
                          </span>
                        </td>
                        <td className="px-4 py-3 font-medium max-w-[160px] truncate">{log.toEmail}</td>
                        <td className="px-4 py-3 text-muted-foreground hidden md:table-cell max-w-[220px] truncate">{log.subject}</td>
                        <td className="px-4 py-3 text-muted-foreground text-xs whitespace-nowrap">{formatTime(log.sentAt)}</td>
                      </tr>
                      {isExpanded && (
                        <tr className="bg-muted/20 border-b border-card-border">
                          <td colSpan={5} className="px-4 py-3">
                            <div className="space-y-1.5 text-xs">
                              <div><span className="text-muted-foreground font-medium">To:</span> {log.toEmail}</div>
                              <div className="md:hidden"><span className="text-muted-foreground font-medium">Subject:</span> {log.subject}</div>
                              {log.errorMessage && (
                                <div className="text-red-600 dark:text-red-400">
                                  <span className="font-medium">Error:</span> {log.errorMessage}
                                </div>
                              )}
                              {log.status === "skipped" && (
                                <div className="text-muted-foreground italic">SMTP not configured — email was logged but not delivered.</div>
                              )}
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
